[versions]
dockerComposePlugInVersion = "0.17.20"
springBootPlugInVersion = "4.0.1"
springDependencyManagementPlugInVersion = "1.1.7"

kafkaE2eeLibraryVersion = '2.3.1'


[libraries]
kafka-e2ee = { module = "de.otto:kafka-messaging-e2ee", version.ref = "kafkaE2eeLibraryVersion" }


[plugins]
dockerCompose = { id = "com.avast.gradle.docker-compose", version.ref = "dockerComposePlugInVersion" }
springBoot = { id = "org.springframework.boot", version.ref = "springBootPlugInVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementPlugInVersion" }
