[versions]
jreleaserPlugInVersion = "1.21.0"

jopenlibsVaultVersion = '6.2.1'
slf4jVersion = '2.0.17'
junitVersion = '6.0.2'
assertJVersion = '3.27.7'


[libraries]
jopenlibs-vault = { module = "io.github.jopenlibs:vault-java-driver", version.ref = "jopenlibsVaultVersion" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jVersion" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jVersion" }

## test libraries
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitVersion" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertJVersion" }


[plugins]
jreleaser = { id = "org.jreleaser", version.ref = "jreleaserPlugInVersion" }